
# TODO: Should be stateful set locally or managed via terraform into streamnative for cloud deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulsar
  namespace: chroma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pulsar
  template:
    metadata:
      labels:
        app: pulsar
    spec:
      containers:
        - name: pulsar
          image: apachepulsar/pulsar
          command: [ "/pulsar/bin/pulsar", "standalone" ]
          env:
          # This is needed by github actions. We force this to be lower everywehre for now.
          # Since real deployments will configure/use pulsar this way.
            - name: PULSAR_MEM
              value: "-Xms128m -Xmx512m"
          ports:
            - containerPort: 6650
            - containerPort: 8080
          volumeMounts:
            - name: pulsardata
              mountPath: /pulsar/data
      volumes:
        - name: pulsardata
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: pulsar
  namespace: chroma
spec:
  ports:
    - name: pulsar-port
      port: 6650
      targetPort: 6650
    - name: admin-port
      port: 8080
      targetPort: 8080
  selector:
    app: pulsar
  type: ClusterIP