apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: memberlists.chroma.cluster
spec:
  group: chroma.cluster
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                members:
                  type: array
                  items:
                    type: object
                    properties:
                      url:
                        type: string
                        pattern: '^(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?$'
  scope: Namespaced
  names:
    plural: memberlists
    singular: memberlist
    kind: MemberList
    shortNames:
      - ml
