# Create a memberlist called worker-memberlist
apiVersion: chroma.cluster/v1
kind: MemberList
metadata:
  name: worker-memberlist
  namespace: chroma
spec:
  members:

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: worker-memberlist-reader
rules:
- apiGroups:
  - chroma.cluster
  resources:
  - memberlists
  verbs:
  - get
  - list
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: worker-memberlist-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: worker-memberlist-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: chroma
