---

apiVersion: v1
kind: Service
metadata:
  name: segment-server
  namespace: chroma
spec:
  ports:
    - name: segment-server-port
      port: 50051
      targetPort: 50051
  selector:
    app: segment-server
  type: ClusterIP

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: segment-server
  namespace: chroma
spec:
  replicas: 2
  selector:
    matchLabels:
      app: segment-server
  template:
    metadata:
      labels:
        app: segment-server
        member-type: worker
    spec:
      serviceAccountName: segmentserver-serviceaccount
      containers:
        - name: segment-server
          image: worker
          imagePullPolicy: IfNotPresent
          command: ["cargo", "run"]
          ports:
            - containerPort: 50051
          volumeMounts:
            - name: chroma
              mountPath: /index_data
          env:
            - name: CHROMA_WORKER__PULSAR_URL
              value: pulsar://pulsar.chroma:6650
            - name: CHROMA_WORKER__MY_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              member-type: worker
      volumes:
        - name: chroma
          emptyDir: {}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: segmentserver-serviceaccount
  namespace: chroma

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: segmentserver-serviceaccount-rolebinding
  namespace: chroma
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-watcher
subjects:
- kind: ServiceAccount
  name: segmentserver-serviceaccount
  namespace: chroma

---