apiVersion: batch/v1
kind: Job
metadata:
  name: sysdb-migration
  namespace: {{ .Values.namespace }}
spec:
  template:
    metadata:
      labels:
        app: sysdb-migration
    spec:
      restartPolicy: OnFailure
      containers:
        - args:
            - 'migrate'
            - 'apply'
            - '--url'
            - "postgres://{{ .Values.sysdbMigration.username }}:{{ .Values.sysdbMigration.password }}@{{ .Values.sysdbMigration.netloc }}:{{ .Values.sysdbMigration.port }}/{{ .Values.sysdbMigration.dbName }}?sslmode={{ .Values.sysdbMigration.sslmode }}"
          image: "{{ .Values.sysdbMigration.image.repository }}:{{ .Values.sysdbMigration.image.tag }}"
          imagePullPolicy: IfNotPresent
          name: migration

---
