[package]
name = "worker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.10"
prost = "0.12"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tokio-util = "0.7.10"
rand = "0.8.5"
rayon = "1.8.0"
kube = { version = "0.87.1", features = ["runtime", "derive"] }
k8s-openapi = { version = "0.20.0", features = ["latest"] }
futures = "0.3"
serde = "1.0.193"
serde_json = "1.0.108"
schemars = "0.8.16"
async-trait = "0.1.74"
pulsar = "6.1.0"
uuid = { version = "1.6.1", features = ["v4", "fast-rng", "macro-diagnostics"] }
murmur3 = "0.5.2"
bytes = "1.5.0"
async-channel = "2.1.1"
num-bigint = "0.4.4"
num-traits = "0.2.17"
parking_lot = "0.12.1"

[build-dependencies]
tonic-build = "0.10"
cc = "1.0"
