name: Check PR Title

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - '**'

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
        - uses: Slashgear/action-check-pr-title@v4.3.0
          with:
            regexp: "\\[ENH|BUG|DOC|TST|BLD|PERF|TYP|CLN|CHORE\\].*"
            helpMessage: "Please tag your PR title. See https://docs.trychroma.com/contributing#contributing-code-and-ideas"
