name: Chroma Coordinator Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - '**'
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: chroma
          POSTGRES_PASSWORD: chroma
          POSTGRES_DB: chroma
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build and test
      run: cd go/coordinator && make test
      env:
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
