name: PR Review Checklist

on:
  pull_request_target:
    types: 
      - opened

jobs:
  PR-Comment:
    runs-on: ubuntu-latest
    steps:
    - name: PR Comment
      uses: actions/github-script@v2
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: ${{ github.event.number }},
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `# Reviewer Checklist
            - [ ] This code is sufficiently tested 
            - [ ] This code is artisanal`
          })
