name: PR Review Checklist
on:
  pull_request_target:
  push:
    branches:
      - main
      - team/hypothesis-tests

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    name: Comment Checklist
    steps:
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: "TEST!"