name: SSH Debug

on:
 push:
    branches:
      - hammad/rust_hnsw_index

jobs:
  debug:
    strategy:
        matrix:
          platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout chroma-hnswlib
      uses: actions/checkout@v3
      with:
        repository: chroma-core/hnswlib
        path: hnswlib
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: chroma
    - name: Install Protoc
      uses: arduino/setup-protoc@v2
    - name: Build
      run: cargo build --verbose
      working-directory: chroma
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
