name: Build and Push Hosted Chroma

on:
 push:
    branches:
      - beggers/hosted-chroma-autodeploy

jobs:
  debug:
    strategy:
        matrix:
          python: ['3.10']
          platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Trigger Hosted Chroma Release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.HOSTED_CHROMA_WORKFLOW_DISPATCH_TOKEN }}
          script: |
            const result = await github.rest.actions.createWorkflowDispatch({
              owner: 'chroma-core',
              repo: 'hosted-chroma',
              workflow_id: 'build-and-publish-image.yaml',
              ref: 'main'
            })
            console.log(result)
