name: SSH Debug

on:
 push:
    branches:
      - beggers/hosted-chroma-autodeploy

jobs:
  debug:
    strategy:
        matrix:
          python: ['3.10']
          platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install test dependencies
      run: python -m pip install -r requirements.txt && python -m pip install -r requirements_dev.txt
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
